ACL/urls.py
from django.urls import path
from .views import *

urlpatterns = []

dashboard_urls = [
    path('dashboard/roles/', RolesListView.as_view(), name='roles-list'),
    path('dashboard/roles/create/', RolesCreateView.as_view(), name='roles-create'),
    path('dashboard/roles/update/<int:pk>/', RolesUpdateView.as_view(), name='roles-update'),
    path('dashboard/roles/delete/<int:pk>/', RolesDeleteView.as_view(), name='roles-delete'),

    path('dashboard/permissions/', PermissionsListView.as_view(), name='permissions-list'),
    path('dashboard/permissions/create/', PermissionsCreateView.as_view(), name='permissions-create'),
    path('dashboard/permissions/update/<int:pk>/', PermissionsUpdateView.as_view(), name='permissions-update'),
    path('dashboard/permissions/delete/<int:pk>/', PermissionsDeleteView.as_view(), name='permissions-delete'),

    path('dashboard/role/user/', RoleUserListView.as_view(), name='role-user-list'),
    path('dashboard/role/user/create/', RoleUserCreateView.as_view(), name='role-user-create'),
    path('dashboard/role/user/update/<int:pk>/', RoleUserUpdateView.as_view(), name='role-user-update'),
    path('dashboard/role/user/delete/<int:pk>/', RoleUserDeleteView.as_view(), name='role-user-delete'),
]

urlpatterns += dashboard_urls

aaa/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ACL/models.py
from django.db import models
# from utils.models import CustomModel
from django.contrib.auth import get_user_model

User = get_user_model()


class Role(models.Model):
    name = models.CharField(max_length=50, verbose_name='نام نمایشی')
    code = models.CharField(verbose_name='عنوان انگلیسی', max_length=255, unique=True)
    description = models.TextField(max_length=500, verbose_name='توضیحات', null=True, blank=True)
    permissions = models.ManyToManyField(to='Permission', related_name='role', verbose_name='نقش ها', blank=True)

    class Meta:
        verbose_name = 'نقش'
        verbose_name_plural = 'نقش ها'

    def __str__(self):
        return f"{self.name}"

    @property
    def permissions_list(self):
        return list(self.permissions.values_list('code', flat=True))


class Permission(models.Model):
    name = models.CharField(max_length=50, verbose_name='نام نمایشی')
    code = models.CharField(verbose_name='عنوان انگلیسی', max_length=255, unique=True)
    description = models.TextField(max_length=500, verbose_name='توضیحات', null=True, blank=True)

    class Meta:
        verbose_name = 'دسترسی'
        verbose_name_plural = 'دسترسی ها'

    def __str__(self):
        return f"{self.name}-{self.code}"


class UserRole(models.Model):
    role = models.ForeignKey(to=Role, on_delete=models.CASCADE, related_name='users', verbose_name='نقش', null=True, blank=True)
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name='role', verbose_name='کاربر')

    class Meta:
        verbose_name = 'نقش کاربر'
        verbose_name_plural = 'نقش کاربران'

    def __str__(self):
        return f"{self.user}-{self.role.name}"

    @property
    def role_name(self):
        if self.role:
            return self.role.name
        return 'کاربر'

ACL/forms.py
from django import forms
from .models import *


class RoleForm(forms.ModelForm):
    permissions = forms.CharField(required=False, label='دسترسی‌ها')

    class Meta:
        model = Role
        fields = '__all__'

    def clean_permissions(self):
        if self.cleaned_data.get('permissions'):
            permissions = self.cleaned_data.get('permissions').split(',')
        else:
            permissions = []

        if len(permissions) == 0:
            raise forms.ValidationError('حداقل یک دسترسی باید در نقش وجود داشته باشد.')

        return permissions


class PermissionForm(forms.ModelForm):
    class Meta:
        model = Permission
        fields = '__all__'


class UserRoleForm(forms.ModelForm):
    class Meta:
        model = UserRole
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance:
            self.fields['user'].queryset = User.objects.filter(role__isnull=True)

ACL/views.py
from django.conf import settings
from django.http import Http404
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from ACL.filters import PermissionFilters, RoleFilters, UserRoleFilters
from ACL.forms import RoleForm, PermissionForm, UserRoleForm
from ACL.models import *
from django.contrib.auth import get_user_model

from ACL.permissions import PERMISSIONS
from ACL.mixins import SuperUserRequiredMixin

User = get_user_model()


class RolesListView(SuperUserRequiredMixin, ListView):
    model = Role
    context_object_name = 'roles'
    paginate_by = settings.PAGINATION_NUMBER
    ordering = ['-updated_at']
    template_name = 'acl/admin/roles/list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return RoleFilters(data=self.request.GET, queryset=queryset).qs


class RolesCreateView(SuperUserRequiredMixin, CreateView):
    model = Role
    template_name = 'acl/admin/roles/form.html'
    form_class = RoleForm
    success_url = reverse_lazy('roles-list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['permissions'] = PERMISSIONS
        return context


class RolesUpdateView(SuperUserRequiredMixin, UpdateView):
    model = Role
    form_class = RoleForm
    template_name = 'acl/admin/roles/form.html'
    success_url = reverse_lazy('roles-list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['permissions'] = PERMISSIONS
        return context


class RolesDeleteView(SuperUserRequiredMixin, DeleteView):
    model = Role
    template_name = 'acl/admin/roles/list.html'
    success_url = reverse_lazy('roles-list')

    def dispatch(self, *args, **kwargs):
        resp = super().dispatch(*args, **kwargs)
        messages.success(self.request, 'نقش مورد نظر با موفقیت حدف شد.')
        return resp


###################################################################

class PermissionsListView(SuperUserRequiredMixin, ListView):
    model = Permission
    context_object_name = 'permissions'
    paginate_by = settings.PAGINATION_NUMBER
    ordering = ['-updated_at']
    template_name = 'acl/admin/permissions/list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return PermissionFilters(data=self.request.GET, queryset=queryset).qs


class PermissionsCreateView(SuperUserRequiredMixin, CreateView):
    template_name = "acl/admin/permissions/form.html"
    model = Permission
    form_class = PermissionForm
    success_url = reverse_lazy("permissions-list")


class PermissionsUpdateView(SuperUserRequiredMixin, UpdateView):
    template_name = "acl/admin/permissions/form.html"
    model = Permission
    form_class = PermissionForm
    success_url = reverse_lazy("permissions-list")


class PermissionsDeleteView(SuperUserRequiredMixin, DeleteView):
    model = Permission
    template_name = 'acl/admin/permissions/list.html'
    success_url = reverse_lazy("permissions-list")

    def dispatch(self, *args, **kwargs):
        resp = super().dispatch(*args, **kwargs)
        messages.success(self.request, 'دسترسی مورد نظر با موفقیت حدف شد.')
        return resp


############################################################################

class RoleUserListView(SuperUserRequiredMixin, ListView):
    model = UserRole
    context_object_name = 'user_roles'
    paginate_by = settings.PAGINATION_NUMBER
    ordering = ['-updated_at']
    template_name = 'acl/admin/user_roles/list.html'
    queryset = UserRole.objects.filter(role__isnull=False)

    def get_queryset(self):
        queryset = super().get_queryset()
        return UserRoleFilters(data=self.request.GET, queryset=queryset).qs


class RoleUserCreateView(SuperUserRequiredMixin, CreateView):
    template_name = "acl/admin/user_roles/form.html"
    model = UserRole
    form_class = UserRoleForm
    success_url = reverse_lazy('role-user-list')

    def get(self, request, *args, **kwargs):
        if self.request.GET.get('user'):
            try:
                User.objects.get(pk=self.request.GET.get('user'))
            except:
                raise Http404

        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return self.success_url


class RoleUserUpdateView(SuperUserRequiredMixin, UpdateView):
    model = UserRole
    form_class = UserRoleForm
    template_name = "acl/admin/user_roles/form.html"
    success_url = reverse_lazy('role-user-list')

    def get(self, request, *args, **kwargs):
        if self.request.GET.get('user'):
            try:
                User.objects.get(pk=self.request.GET.get('user'))
            except:
                raise Http404

        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return self.success_url


class RoleUserDeleteView(SuperUserRequiredMixin, DeleteView):
    model = UserRole
    template_name = 'acl/admin/user_roles/list.html'
    success_url = reverse_lazy('role-user-list')

    def dispatch(self, *args, **kwargs):
        resp = super().dispatch(*args, **kwargs)
        messages.success(self.request, 'کاربر مدیر مورد نظر با موفقیت حدف شد.')
        return resp

ACL/templates/acl/admin/roles/form.html
{% extends 'Layouts/admin-master.html' %}
{% load i18n public_tags acl_tags %}

{% block title %} {% if object %}ویرایش نقش{% else %}افزودن نقش{% endif %} {% endblock %}

{% block content %}

    <div class="row" ng-init="init()">
        <div class="col-xs-12">
            <div class="col-lg-12">
                <div class="card-box">
                    <h2 class="card-title"><b>{% if object %}ویرایش نقش{% else %}افزودن نقش جدید{% endif %}</b></h2>

                    <form class="form-horizontal"
                          method="post" id="frm"
                          enctype="multipart/form-data">

                        {% csrf_token %}

                        {% for field in form %}
                            {% if field.name != 'permissions' %}
                                <div class="form-group">
                                    <label class="control-label col-lg-2"
                                           for="id_{{ field.name }}">{{ field.label }}:</label>

                                    <div class="col-md-10">
                                        {{ field|addclass:"form-control" }}

                                        {% if field.help_text %}
                                            <p><small style="font-size: 14px">{{ field.help_text|safe }} </small></p>
                                        {% endif %}
                                        {% if field.errors %}
                                            <p><small class="text-danger" style="font-size: 14px"
                                                      style="color:red">{{ field.errors.0|safe }}</small></p>
                                        {% endif %}
                                        {% if field.non_field_errors %}
                                            <p><small class="text-danger" style="font-size: 20px"
                                                      style="color:red">{{ field.non_field_errors.0|safe }}</small></p>
                                        {% endif %}
                                    </div>
                                </div>
                            {% else %}
                                <input type="hidden" name="permissions" id="id_permissions">
                            {% endif %}
                        {% endfor %}

                        <hr/>
                        <div class="row mt-5 container">
                            <div class="col-md-12 mb-5">
                                <h4>
                                    <i class="fa fa-list"></i>
                                    دسترسی‌های مورد نظر را از لیست زیر انتخاب کنید.
                                </h4>
                            </div>

                            {% parse_permission form.permissions.value as permissions_list %}

                            {% for item in permissions %}
                                <div class="col-md-12"
                                     style="margin-right: 200px !important; margin-top: 30px !important;">
                                    <p class="font-weight-bold" ng-if="role.is_editable"> مدیریت
                                        دسترسی‌های {{ item.title }}</p>
                                    <p class="font-weight-bold" ng-if="!role.is_editable">
                                        {{ item.title }}</p>
                                    <div class="row">
                                        {% for perm in item.permissions %}
                                            {% get_permission_id perm.code as perm_id %}
                                            <div class="col-md-4 m-t-5">
                                                <label class="font-weight-light"
                                                       for="id_permissions_{{ perm.code }}">{{ perm.name }}</label>
                                                &nbsp;
                                                <label class="custom-switch">
                                                    <input type="checkbox" name="custom-switch-checkbox"
                                                           id="id_permissions_{{ perm.code }}"
                                                            {#                                                           ng-model="perms.{{ perm.name }}"#}
                                                           {% if perm_id|check_perm_selected:permissions_list %}checked{% endif %}
                                                           ng-click="permListChange('{{ perm_id }}')"
                                                           class="custom-switch-input">
                                                    {#                                                    <input type="checkbox" name="custom-switch-checkbox"#}
                                                    {#                                                           ng-model="perms.{{ perm.name }}"#}
                                                    {#                                                           class="custom-switch-input">#}
                                                    <span class="custom-switch-indicator"></span>
                                                </label>
                                                <h6><small>{{ perm.description|default_if_none:'' }}</small>
                                                </h6>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}

                            {% if form.permissions.errors %}
                                <p style="margin-right: 200px !important; margin-top: 30px !important;"><small class="text-danger" style="font-size: 14px"
                                          style="color:red">{{ form.permissions.errors.0|safe }}</small></p>
                            {% endif %}
                        </div>


                        <div class="col-lg-12">
                            <div class="m-1-25 m-b-20" style="float: left !important;">
                                <a href="{{ request.META.HTTP_REFERER }}"
                                   class="btn btn-danger btn-border-radius waves-effect">
                                    بازگشت
                                </a>
                                <button class="btn btn-info btn-border-radius waves-effect" ng-click="submit()"
                                        type="button">ثبت
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

{% block Scripts %}
    <script>
        app.controller('myCtrl', function ($scope, $http) {
            $scope.permsList = [];
            $scope.permissions = '';
            $scope.perms = {};

            $scope.init = function () {
                {% if form.permissions.value %}
                    {% parse_permission_str_list form.permissions.value as permissions_str_list %}
                    $scope.permsList = '{{ permissions_str_list }}'.split(',');
                {% endif %}
            }

            $scope.permListChange = function (permID) {
                let index = $scope.permsList.indexOf(permID);
                if (index > -1) {
                    $scope.permsList.splice(index, 1);
                } else {
                    $scope.permsList.push(permID)
                }

                $scope.permissions = $scope.permsList.join();
                $("#id_permissions").val($scope.permsList.join())
                console.log($scope.permsList)
            };

            $scope.submit = function () {
                $("#id_permissions").val($scope.permsList.join())
                $('#frm').submit();
            }
        });
    </script>
    <script>
        {#$("#id_permissions").select2();#}
    </script>
{% endblock %}

ACL/templates/acl/admin/roles/list.html
{% extends 'Layouts/admin-master.html' %}
{% load static public_tags %}

{% block title %} لیست نقش ها {% endblock %}

{% block content %}

    <div class="row">

        {% if messages %}
            {% for item in messages %}
                <script>
                    Swal.fire({
                        title: "تبریک ! 🥳",
                        icon: 'success',
                        text: '{{ item }}',
                        type: "success",
                        cancelButtonColor: 'var(--primary)',
                        confirmButtonText: 'اوکی',
                    })
                </script>
            {% endfor %}
        {% endif %}

        <div class="col-lg-12">
            <div class="card-box">
                <div class="card-block">
                    <h4 class="card-title">لیست نقش ها</h4>

                    <hr>
                    <form id="search">
                        <div class="form-group">
                            <div class="row">
                                {% include 'Admin/Filters/search_input.html' %}
                                {% include 'Admin/Filters/limit_select_box.html' %}
                            </div>
                        </div>
                    </form>

                    <a class="btn btn-primary pull-right" href="{% url 'roles-create' %}">افزودن نقش جدید</a>

                    <span id="list">
                     {% if object_list %}
                         <table class="table table-hover">
    <thead>
    <tr>
    <th>ردیف</th>
    <th>نام نمایشی</th>
    <th>عنوان انگلیسی</th>
    <th>توضیحات</th>
    <th>اعمال</th>
    </tr>
    </thead>
    <tbody>

    {% for item in object_list %}
        <tr>
        <td>{{ forloop.counter }}</td>

        <td>{{ item.name | default:'---' }}</td>

        <td>{{ item.code | default:'---' }}</td>

        <td title="{{ item.description }}">{{ item.description | default:'---' | truncatechars:'50' }}</td>

        <td>
            <div class="buttons ">
                <form action="{% url 'roles-delete' item.id %}"
                      id="delete_form_{{ item.id }}"
                      method="post">
                    {% csrf_token %}

                    <a href="{% url 'roles-update' item.id %}"
                       class="btn btn-primary btn-action mr-1"
                       data-toggle="tooltip" title=""
                       data-original-title="ویرایش"><i
                            class="fas fa-pencil-alt"></i><i
                            class="fa fa-pencil"> </i> </a>
                    <button type="button"
                            data-original-title="حذف"
                            data-toggle="tooltip"
                            onclick="DeleteConfirm('{{ item.id }}')"
                            class="delete_button btn btn-danger btn-action"><i
                            class="fa fa-trash"> </i>
                    </button>
                </form>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
                     {% else %}
                         <h4 style="text-align: center; padding: 40px">
                                موردی یافت نشد.
                         </h4>
                     {% endif %}

                        {% include 'Admin/pagination.html' with page_obj=page_obj %}
                    </span>

                    {#                    {% include 'Admin/Users/partials/list.html' with page_obj=page_obj users=users %}#}

                </div>
            </div>
        </div>

    </div>

{% endblock %}

{% block Scripts %}
    <script>
        function DeleteConfirm(id) {
            Swal.fire({
                title: "هشدار ! ",
                icon: 'warning',
                text: "آیا از حذف این آیتم اطمینان دارید؟",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: '#00aced',
                cancelButtonColor: '#e6294b',
                confirmButtonText: 'حذف',
                cancelButtonText: 'انصراف'
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#delete_form_' + id).submit();
                }
            })
        }
    </script>
{% endblock %}